FROM python:3.10-slim

WORKDIR /mlflow

COPY requirements.mlflow.in .
RUN pip install --no-cache-dir -r requirements.mlflow.in

COPY . .

# Exposer le port par défaut de MLflow
EXPOSE 5000

# Commande pour lancer MLflow UI
CMD ["mlflow", "ui", "--host", "0.0.0", "--port", "5000"]
