FROM apache/airflow:3.0.6

# Définir le répertoire de travail
WORKDIR /airflow

# kaggle key
USER root
RUN mkdir -p /home/airflow/.kaggle
COPY keys/kaggle.json /home/airflow/.kaggle/kaggle.json
RUN chmod 600 /home/airflow/.kaggle/kaggle.json && chown airflow: /home/airflow/.kaggle/kaggle.json
USER airflow

# Copier les requirements spécifiques à Airflow
COPY requirements.airflow.in .
RUN pip install --no-cache-dir -r requirements.airflow.in

# Copier le code (DAGs, scripts, etc.)
COPY . .

# Exposer le port web d’Airflow
EXPOSE 8080

# Définir les variables d’environnement recommandées
ENV AIRFLOW_HOME=/airflow
ENV AIRFLOW__CORE__LOAD_EXAMPLES=False
ENV AIRFLOW__CORE__EXECUTOR=LocalExecutor
ENV AIRFLOW_UID=50000
ENV _AIRFLOW_WWW_USER_USERNAME=admin
ENV _AIRFLOW_WWW_USER_PASSWORD=admin
ENV PYTHONPATH=src/movie_recommender

# Démarrer Airflow en standalone (webserver + scheduler dans 1 process)
CMD ["airflow", "standalone"]
